### ISSUE TITLE
Suggestion: Mod support for right click dyeing

### ISSUE THREAD

**Issue by stohun01** [Lilylicious/MysteriousMiscellany#14]
Detect dyes (dyeing item not blocks) based on the ore dictionary

Add dyeing of modded blocks via config based on individual block ID or ore dictionary with a section in the config for each of the 16 colours. Example:

`Magenta {
ModID:blockWhite, ModID:blockMagenta;
OtherModID:stone, OtherModID:purpleStone
}`

**Comment by Lilylicious** [comment]
I like this idea.

To clarify, the first bit was about making the dye recognize oredict for the dye (e.g botania floral powder), while the second part was about adding a confit ability to add conversions based on dye held?

Do you have an example of a dyeable block from another mod I can test with?

**Comment by stohun01** [comment]
You are correct. I would suggest testing with Chisel, there are plenty of stained glass variants and the Antiblocks.

**Comment by Lilylicious** [comment]
Adding in a block>other block config should be no problem. The only problem I can think of would be if I wanted to limit what blocks can turn into. Theoretically, the easiest implementation of this would be to just convert between blocks. That would mean you could add that white dye turns stone into diamond.

Could limit it to changing metadata, but there are cases where that isn't enough in vanilla. Hardened clay is a completely separate item than stained hardened clay, for example.

**Comment by stohun01** [comment]
I think it would be easier left open for people to configure it themselves. Take MineTweaker for example, you could easily create a script that turns dirt into gold blocks

**Comment by Lilylicious** [comment]
True. I'll open up the ability to configure additional dye recipes. If people abuse it to unbalance things, that's on them not me. Honestly, I think I'll make an API in addition to a config file. Let people add infusion recipes too.

 Thanks!

**Comment by Lilylicious** [comment]
Mod will not be further developed, due to me moving onto other projects.
