### ISSUE TITLE
Feature Request: Enchanting Tables can store lapis

### ISSUE THREAD

**Issue by stohun01** [Lilylicious/MysteriousMiscellany#15]

**Comment by Lilylicious** [comment]
Hard to do, as it'd be modifying the behavior of a vanilla block. I couuuuld theoretically make an alternative to the enchanting table, but doing it for the sole purpose of storing lapis seems excessive.

**Comment by stohun01** [comment]
fair enough

**Comment by Lilylicious** [comment]
If I do end up making an alternative method of enchanting items, I'll definitely keep something like this in mind.
