### ISSUE TITLE
Bug: Dye with any number of items

### ISSUE THREAD

**Issue by MindCaged** [Lilylicious/MysteriousMiscellany#17]
I noticed a bug which I believe is caused by this feature. I installed Modular Powersuits in 1.10.2 and when I try to set the recipe to craft solar panels in my Refined Storage system, it instead tries to craft dyed glass, the recipe has both lapis and glass in the recipe. Modular Powersuits I believe uses a custom recipe system so you can set custom recipes, so it might not be working properly with whatever system you use to check if there's another valid recipe before doing the dyed item recipe.

It might be good if your recipe checked to make sure there was only 1 dye and all the other items were the same. I notice that if I put 4 dye, 4 glass, and a piece of cobble it'll return the dyed glass and eat the cobble. In the meantime I just disabled the dye function in the config as I don't use it too often.

**Comment by Lilylicious** [comment]
Interesting. I thought I had made it not work with extra items. I'll look into it tonight.

**Comment by MindCaged** [comment]
Hmm, I didn't try it with a normal crafting table, maybe because I was using Refined Storage? I'm not sure how the recipe system works internally as I'm not a modder.

**Comment by Lilylicious** [comment]
So I was actually considering leaving this, as it felt like a big bug and I've moved on to other projects, but..

The fix was two lines. else, return false. That's it. Huh.

Fixed in the latest versions for both 1.10.2 and 1.11.2
