### ISSUE TITLE
FYI?

### ISSUE THREAD

**Issue by Nexusdog** [Lilylicious/MysteriousMiscellany#18]
I've seen this in my crash logs, dunno if it's useful or not?

* The RF API that is being used (1.6.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from MysteriousMiscellany-1.10.2-1.5.4.jar).

**Comment by Lilylicious** [comment]
Is the crash caused by Mysterious Miscellany? Does it stop crashing when you remove the mod? If so, can I see the entire crash log?
