### ISSUE TITLE
Grass stomping and Biomes O Plenty.

### ISSUE THREAD

**Issue by Chaogomu** [Lilylicious/MysteriousMiscellany#19]
In Minecraft 1.11.2  With Biomes O Plenty 6.1.0.2222 and Mysterious Miscellany 1.1.4

Grass stomping has no effect on all the extra grass types added by Biomes O Plenty.

**Comment by Lilylicious** [comment]
As of right now, there is no compatibility with any grass types other than vanilla. This may change in the future.
