### ISSUE TITLE
Compressed Bookshelves not placeable in all locations

### ISSUE THREAD

**Issue by Zygus42** [Lilylicious/MysteriousMiscellany#5]
Both types of compressed bookshelves only appear to work exactly 2 spaces away directly behind the enchanting table, not in any of the other locations you can usually put library bookshelves in.

**Comment by Lilylicious** [comment]
Can't seem to replicate this. It seems odd that it'd be the case too, the only difference between the compressed and normal bookshelves is that the compressed versions say a higher number when asked about their enchanting power.

For this to be happening, the enchanting table would need to not ask about the spot the bookshelf is in. Is it a vanilla enchanting table?

Lastly, thanks for reporting this! The only thing better than my mod being used is people helping to improve it.

**Comment by Zygus42** [comment]
Tested again, and realised that I had grass in the way, so entirely my fault, not yours !  Thanks for the reply.
