### ISSUE TITLE
Feature Request:  Ability to turn off items in config

### ISSUE THREAD

**Issue by Zygus42** [Lilylicious/MysteriousMiscellany#6]
Really want to use this mod, but needs the ability to switch off certain items in the config.  The one that really breaks our world in particular is the ice spreader (which really should be called the ocean annihilator instead, as an ice spreader would turn the water to ice, not destroy it), but other people are going to have problems with other items in their builds as well.

**Comment by Lilylicious** [comment]
Will disabling the recipes do it for you? If so, it's code ready. Just need to do some testing before release, but should have that done before tonight. All recipes (including dyeing items and stuff) will have an off switch in configs.

**Comment by Zygus42** [comment]
Off would do, but changing to smaller radius would be better as it's an interesting feature.

**Comment by Lilylicious** [comment]
I also added a config for it. And changed the name, your suggestion IS more accurate.
